// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_mig_writer_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_mig_writer_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202310162053106_add_mig_writer_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
